.TH "NUMONIC-CONTAINER" "7" "November 10, 2021" "Numonic
v8.1.0" "Numonic Manual"
.nh \" Turn off hyphenation by default.
.SH NAME
.PP
numonic-container - a collection of utilities for managing containers
for both docker and podman
.SH SYNOPSIS
.PP
numonic-container
.SH DESCRIPTION
.PP
Numonic includes a few utilities to make managing container images
easier in development worksflows.
These utilties work with both docker and podman.
If both container cli tools are available, then the commands will
operate on both at the same time.
.SH SEE ALSO
.PP
\f[B]container-gc\f[R](1), \f[B]container-update\f[R](1)
.SH AUTHORS
Deavon M. McCaffery; Not Committed Yet
