.TH "NUMONIC-GIT" "7" "February 1, 2022" "Numonic 0.0.1-alpha" "Numonic
Manual"
.nh \" Turn off hyphenation by default.
.SH NAME
.PP
numonic-git - a collection of extensions for the git cli that make it
easier to work with forks and pull requests
.SH SYNOPSIS
.PP
numonic-git
.SH DESCRIPTION
.PP
Numonic includes a large collection of extensions to the git cli that
make operating with forks and pull requests even easier.
These extensions are available via the git cli itself and can be aliased
for even shorter names, if you so choose.
They are also tied into the git help system.
For example, \f[C]man git-fork-clone\f[R] or
\f[C]git fork-clone --help\f[R] will both pull up the manual for the
\f[C]fork-clone\f[R] extension.
.SH AVAILABLE COMMANDS
.PP
checkout-branch - a command used to create and switch to a new local
branch
.SH AUTHORS
Scott K. Garan
