.TH "EDIT-ZSHRC" "1" "November 10, 2021" "Numonic v8.1.0" "Numonic
Manual"
.nh \" Turn off hyphenation by default.
.SH NAME
.PP
edit-zshrc - opens an editor to the user-specific bash run commands
script
.SH SYNOPSIS
.PP
\f[I]edit-zshrc\f[R]
.SH DESCRIPTION
.PP
This command will open the editor defined by the \f[B]EDITOR\f[R]
environment variable.
If the variable is not set then the default editor will be \f[B]vi\f[R]
.SH EXAMPLES
.PP
edit-zshrc
.SH SEE ALSO
.PP
\f[B]zsh\f[R](1), \f[B]editor\f[R](1)
.SH AUTHORS
Deavon M. McCaffery
