.TH "GIT-COMMIT-SAVE" "1" "February 1, 2022" "Numonic
0.0.1-alpha" "Numonic Manual"
.nh \" Turn off hyphenation by default.
.SH NAME
.PP
git-commit-save - create a new empty marker commit
.SH SYNOPSIS
.PP
\f[B]git\f[R] \f[B]commit-save\f[R] [\f[B]--dry-run\f[R]]
[\f[B]--debug\f[R]] [\f[B]--help\f[R]]
.SH DESCRIPTION
.PP
This command creates a new checkpoint commit with a prefix of
\f[B][SAVE]\f[R] for the subject.
This is useful for saving progress as a new commit on the current HEAD
without pushing to the remote.
A saved commit is only retained locally.
.SH OPTIONS
.SS <message>, -m <message>, --message=<message>
.PP
the message to include in the save commit
.SS --help
.PP
print this help information
.SS --debug
.PP
print the commands as they are executed (set -x)
.SH EXAMPLES
.SS git commit-wip
.PP
create an save commit with a subject of: \f[B][SAVE]\f[R] which is not
pushed to the remote
.SS git commit-wip -d \[aq]some message\[aq]
.SS git commit-wip --debug some message
.PP
create a commit with a subject of: \f[B][SAVE] some message\f[R] and
push to the remote while printing the commands as they are executed
.SH SEE ALSO
.PP
\f[B]git-commit-mark\f[R](1), \f[B]git-commit-wip\f[R](1),
\f[B]git-commit-restore\f[R](1), \f[B]git-commit-undo\f[R](1),
\f[B]git-commit\f[R](1)
.SH AUTHORS
Scott K. Garan
