.TH "USERENV-GET" "1" "November 10, 2021" "Numonic v8.1.0" "Numonic
Manual"
.nh \" Turn off hyphenation by default.
.SH NAME
.PP
userenv-get - gets the value of a variable within the user specific
environment file
.SH SYNOPSIS
.PP
\f[B]userenv get\f[R] <\f[I]key\f[R]> [\f[B]--help\f[R]]
.SH DESCRIPTION
.PP
This command will retrieve the current value of a variable as defined
within the user specific environment file, typically located at
$HOME/.pam_environment.
This command is case-sensitive as variables are also case sensitive.
.SH OPTIONS
.SS <key>
.PP
the key (or name) of the environment variable to get
.SS --help
.PP
print this help information
.SH EXAMPLES
.SS userenv get PATH
.PP
get the value of the PATH variable within the user specific environment
file
.SH SEE ALSO
.PP
\f[B]userenv-add\f[R](1), \f[B]userenv-edit\f[R](1),
\f[B]userenv-set\f[R](1), \f[B]userenv-load\f[R](1),
\f[B]pam_env\f[R](7)
.SH AUTHORS
Deavon M. McCaffery
