#! /usr/bin/env sh

set -e

__numonic_container_update() {
	while :; do
		case $1 in
			-q|--quiet)
				quiet=1
				;;
			-d|--debug)
				debug=1
				;;
			-h|--help)
				man container-update
				return 0
				;;
			*?)
				print-fail "container-update: unknown argument ${1}"
				man container-update | cat 1>&2
				return 1
				;;
			*)
				break;
		esac
		shift
	done

	if command -v podman 1>/dev/null 2>&1; then
		(
			if [ -n "${debug:-}" ]; then
				set -x
			fi

			if [ -n "${quiet:-}" ]; then
				exec 1>/dev/null
			fi

			print-warn 'container-update: updating images in podman...' 2>&1

			podman image ls --filter dangling=false \
				--format "{{.Repository}}:{{.Tag}}" | xargs -L1 podman pull 2>/dev/null
		) || true

		found=1
	fi

	if command -v docker 1>/dev/null 2>&1; then
		(
			if [ -n "${debug:-}" ]; then
				set -x
			fi

			if [ -n "${quiet:-}" ]; then
				exec 1>/dev/null
			fi

			print-warn 'container-update: updating images in docker...' 2>&1

			docker image ls --filter dangling=false \
				--format "{{.Repository}}:{{.Tag}}" | xargs -L1 docker pull 2>/dev/null
		) || true

		found=1
	fi

	if [ -z "${found:-}" ]; then
		print-fail 'container-update: neither podman nor docker were available on the path.'
		man container-update | cat 1>&2
		return 1
	fi
}

__numonic_container_update "$@"
