#! /usr/bin/env sh

set -e

__numonic_container_gc() {
	while :; do
		case $1 in
			-d|--debug)
				debug=1
				;;
			-q|--quiet)
				quiet=1
				;;
			-h|--help)
				man container-gc
				return 0
				;;
			*?)
				print-fail "container-gc: unknown argument ${1}"
				man container-gc | cat 1>&2
				return 1
				;;
			*)
				break;
		esac
		shift
	done

	if command -v buildah 1>/dev/null 2>&1; then
		(
			# shellcheck disable=SC2030,SC2031
			if [ -n "${debug:-}" ]; then
				set -x
			fi

			if [ -n "${quiet:-}" ]; then
				exec 1>/dev/null
			fi

			print-warn 'container-gc: garbage collecting buildah...' 2>&1

			# todo: replace with external prune when available
			# see: https://github.com/containers/podman/pull/11737
			buildah rm --all
		) || true
	fi

	if command -v podman 1>/dev/null 2>&1; then
		(
			# shellcheck disable=SC2030,SC2031
			if [ -n "${debug:-}" ]; then
				set -x
			fi

			if [ -n "${quiet:-}" ]; then
				exec 1>/dev/null
			fi

			print-warn 'container-gc: garbage collecting podman...' 2>&1

			podman container prune --force 2>/dev/null
			podman volume prune --force 2>/dev/null
			podman image prune --force 2>/dev/null
		) || true

		found=1
	fi

	if command -v docker 1>/dev/null 2>&1; then
		(
			# shellcheck disable=SC2030,SC2031
			if [ -n "${debug:-}" ]; then
				set -x
			fi

			if [ -n "${quiet:-}" ]; then
				exec 1>/dev/null
			fi

			print-warn 'container-gc: garbage collecting docker...' 2>&1

			docker container prune --force 2>/dev/null
			docker volume prune --force 2>/dev/null
			docker image prune --force 2>/dev/null
		) || true

		found=1
	fi

	if [ -z "${found:-}" ]; then
		print-fail 'container-gc: neither podman nor docker were available on the path.'
		man container-gc | cat 1>&2
		return 1
	fi
}

__numonic_container_gc "$@"
