#! /usr/bin/env sh

set -e

__numonic_git_commit_undo() {
	while :; do
		case $1 in
			-d|--debug)
				debug=1
				;;
			-h|--help)
				man git commit-undo
				return 0
				;;
			*?)
				print-fail "git commit-undo: unknown argument ${1}"
				man git commit-undo | cat 1>&2
				return 1
				;;
			*)
				break;
		esac
		shift
	done

	(
		if [ -n "${debug:-}" ]; then
			set -x
		fi

		git reset HEAD~1 --mixed
	)
}

__numonic_git_commit_undo "$@"
