#! /usr/bin/env sh

set -e

__numonic_git_update() {
	positional=

	while :; do
		case $1 in
			-d|--debug)
				debug=1
				;;
			-h|--help)
				man git-update
				return 0
				;;
			*?)
				if [ -z "${positional:-}" ]; then
					positional="${1}"
				else
					positional="${positional} ${1}"
				fi
				;;
			*)
				break;
		esac
		shift
	done

	# shellcheck disable=SC2086
	set -- ${positional}

	(
		if [ -n "${debug:-}" ]; then
			set -x
		fi

		git fetch --prune --prune-tags
		git pull --rebase "$@"
		git submodule update --init --recursive
	)
}
