#! //usr/bin/env sh

set -e

__numonic_print_success()
{
	printf '%s' "${CLR_SUCCESS}"
	printf '%s\n' "$@"
	printf '%s' "${FORMAT_NO_TTY}${CLR_SUCCESS}${FORMAT_CLEAR}"
}

__numonic_print_success "$@"
