#! /usr/bin/env sh

__numonic_hide_all() {
	while :; do
		case $1 in
			--debug)
				debug=1
				;;
			--help)
				man hide-all
				return 0
				;;
			*?)
				print-fail "hide-all: unknown argument ${1}"
				man hide-all | cat 1>&2
				return 1
				;;
			*)
				break;
		esac
		shift
	done

	(
		if [ -n "${debug:-}" ]; then
			set -x
		fi

		defaults write com.apple.finder AppleShowAllFiles FALSE
		killall Finder
	)
}

__numonic_hide_all "$@"
