#! /usr/bin/env sh

set -e

__numonic_install_pandoc() {
	print-success 'install-pandoc: installing cli...'
	brew install pandoc librsvg
	brew tap homebrew/cask
	brew install basictex
	eval "$(/usr/libexec/path_helper -s)"

	print-warn '' 'You will be asked for admin credentials to install tex plugins' ''

	sudo tlmgr update --self
	sudo tlmgr install texliveonfly
	sudo tlmgr install xelatex
	sudo tlmgr install adjustbox
	sudo tlmgr install tcolorbox
	sudo tlmgr install collectbox
	sudo tlmgr install ucs
	sudo tlmgr install environ
	sudo tlmgr install trimspaces
	sudo tlmgr install titling
	sudo tlmgr install enumitem
	sudo tlmgr install rsfs
}

__numonic_install_pandoc "$@"
